version: 2

models:
  - name: stg_local_bike__brands
    description: "This model contains information about bikes brand"
    columns:
      - name: brand_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null

  - name: stg_local_bike__categories
    description: "This model contains information about bikes categories"
    columns:
      - name: category_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null  
      
  - name: stg_local_bike__customers
    description: "This model contains customers personal informations"
    columns:
      - name: customer_id
        description: "Primary key, unique identifier for each brand"
        tests:
            - unique
            - not_null  

  - name: stg_local_bike__order_items
    description: "This model contains information about each item included in an order, including its price, quantity, and discount."
    columns:
      - name: order_item_id
        description: "Primary key, unique identifier for each order item.generated by concatenating item_id and order_id."
        tests:
            - unique
            - not_null
      - name: order_id
        description: "Foreign key linking the order item to the corresponding order."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__orders')
                field: order_id
      - name: sale_price
        description: "The effective selling price of each bicycle after applying the discount; calculated as (list_price - (list_price * discount))"
      - name: order_item_amount
        description: "The total amount for this order item, calculated as (sale_price * quantity)."
      
  - name: stg_local_bike__orders
    description: "This model contains information about orders placed by users, including the status of each order."
    columns:
      - name: order_id
        description: "Primary key, unique identifier for each order."
        tests:
            - unique
            - not_null
      - name: order_status
        description: "The current status of the order."
        tests:
          - accepted_values:
              arguments:
               name: accepted_values_order_status
               values: [1, 2, 3, 4]
      - name: customer_id
        description: "Foreign key linking the order to the customer who placed it."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__customers')
                field: customer_id
      - name: store_id
        description: "Foreign key linking the order to the store where it was purchased."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__stores')
                field: store_id
      - name: staff_id
        description: "Foreign key linking the order to the staff that sold it."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__staffs')
                field: staff_id

  - name: stg_local_bike__products
    description: "This model contains details of bikes available for sale (name, model and price)."
    columns:
      - name: product_id
        description: "Primary key, unique identifier for each product."
        tests:
            - unique
            - not_null
      - name: brand_id
        description: "Foreign key linking the product to the brand it belong to."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__brands')
                field: brand_id
      - name: category_id
        description: "Foreign key linking the product to the category it belong to."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__categories')
                field: category_id
  
  - name: stg_local_bike__staffs
    description: "This model contains personal information about sales team."
    columns:
      - name: staff_id
        description: "Primary key, unique identifier for each staff."
        tests:
            - unique
            - not_null

  - name: stg_local_bike__stocks
    description: "This model contains personal information about the stock."
    columns:
      - name: stock_id
        description: "Primary key, unique identifier for each products soctk .generated by concatenating store_id and product_id."
        tests:
            - unique
            - not_nullll
      - name: store_id
        description: "Foreign key linking the stock to each store."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__stores')
                field: store_id
      - name: product_id
        description: "Foreign key linking the product to the stock."
        tests:
          - relationships:
              arguments:
                to: ref('stg_local_bike__products')
                field: product_id

  - name: stg_local_bike__stores
    description: "This model contains informations about all the stores in the cities where the bikes are sold.."
    columns:
      - name: store_id
        description: "Primary key, unique identifier for each store."
        tests:
            - unique
            - not_null
      