version: 2

snapshots:
  - name: snps_local_bike__monthly_stocks
    description: "Historical snapshot of product stock levels."
    columns:
      - name: product_id
        description: "Unique identifier of the product."
        tests:
          - not_null

      - name: stock_qty
        description: "Quantity available in stock at the time of snapshot."
        tests:
          - stockout:
              config:
                severity: warn
